### ISSUE TITLE
翻墙路好崎岖——必须先编译gfw-vpn的rom，刷好再编译没gfw-vpn的rom，再逐步安装配置

### ISSUE THREAD

**Issue by zhiyin-im** [hackgfw/openwrt-gfw#25]
直接编译了gfw-vpn刷机无法连vpn而且没有任何出错信息；
去掉gfw-vpn再编译刷机，装gfw-vpn.ipk还是无法连vpn而且没有任何出错信息；
去掉gfw-vpn再编译刷机，逐步安装配置，可以连vpn但无法访问google；
以前都使用sysupgrade -c sysupgrade.bin保留了配置文件，所以这次用factory.bin覆盖，结果还是无法连vpn而且没有任何出错信息；
再加上gfw-vpn编译，用factory.bin覆盖；再去掉gfw-vpn编译，用sysupgrade -c sysupgrade.bin升级并保留配置文件；然后逐步安装配置，可以连vpn但无法访问google；
修改mtu终于可以正常访问google了。。。

到底什么原因？能否提供真正的傻瓜rom？这个过程对普通人太崎岖。
做了这么久翻墙先烈，终于成为了翻墙先驱了。。。

**Comment by texnician** [comment]
我照着PPTPVPN做了一遍，发现没有任何效果啊
你说的那个ip-up-wall脚本在哪?什么时候运行的？

**Comment by hackgfw** [comment]
@texnician 
ip-up-wall 是在 vpn 连接后运行的，你需要先在 /etc/config/gfw-vpn 里配置 vpn 接口名，使其和 /etc/config/network 中的一致

**Comment by texnician** [comment]
谢谢回复，已经解决啦~

2015-01-19 23:52 GMT+08:00 hackgfw <notifications@github.com>:
