### ISSUE TITLE
gfw-dns直接刷机不能用，恐怕也得像gfw-vpn一样逐步配置。。。

### ISSUE THREAD

**Issue by zhiyin-im** [hackgfw/openwrt-gfw#26]
root@OpenWrt:~# iptables -L protectdns
Chain protectdns (2 references)
target     prot opt source               destination         
DROP       all  --  anywhere             anywhere             u32 "0x4&0x1fff=0x0&&0x0>>0x16&0x3c@0x8&0x8000=0x8000&&0x0>>0x16&0x3c@0xe=0x0"
DROP       all  --  anywhere             anywhere             STRING match  "|31027b38|" ALGO name bm FROM 60 TO 500
DROP       all  --  anywhere             anywhere             STRING match  "|cb620741|" ALGO name bm FROM 60 TO 500
DROP       all  --  anywhere             anywhere             STRING match  "|fd9d0ea5|" ALGO name bm FROM 60 TO 500
DROP       all  --  anywhere             anywhere             STRING match  "|f3b9bb27|" ALGO name bm FROM 60 TO 500
DROP       all  --  anywhere             anywhere             STRING match  "|2e52ae44|" ALGO name bm FROM 60 TO 500
DROP       all  --  anywhere             anywhere             STRING match  "|042442b2|" ALGO name bm FROM 60 TO 500
DROP       all  --  anywhere             anywhere             STRING match  "|bda31105|" ALGO name bm FROM 60 TO 500
DROP       all  --  anywhere             anywhere             STRING match  "|bc050460|" ALGO name bm FROM 60 TO 500
DROP       all  --  anywhere             anywhere             STRING match  "|5d2e0859|" ALGO name bm FROM 60 TO 500
DROP       all  --  anywhere             anywhere             STRING match  "|4a7d7f66|" ALGO name bm FROM 60 TO 500
DROP       all  --  anywhere             anywhere             STRING match  "|0807c62d|" ALGO name bm FROM 60 TO 500
DROP       all  --  anywhere             anywhere             STRING match  "|3b1803ad|" ALGO name bm FROM 60 TO 500
DROP       all  --  anywhere             anywhere             STRING match  "|7f000001|" ALGO name bm FROM 60 TO 500
DROP       all  --  anywhere             anywhere             STRING match  "|253d369e|" ALGO name bm FROM 60 TO 500
root@OpenWrt:~# dig: couldn't get address for 'www.twitter.com': not found
dig: couldn't get address for 'twitter.com': not found
dig: couldn't get address for 'www.facebook.com': not found
dig: couldn't get address for 'youtube.com': not found
dig: couldn't get address for 'encrypted.google.com': not found
dig: couldn't get address for 'plus.google.com': not found
dig: couldn't get address for 'www.openvpn.net': not found
dig: couldn't get address for 'openvpn.net': not found
 dig: couldn't get address for 'svn.openvpn.net': not found
dig: couldn't get address for 'shell.cjb.net': not found

**Comment by hackgfw** [comment]
GFW 升级，gfw-dns已失效
