### ISSUE TITLE
每次都要连N次VPN，先建立MTU:1500，断N次后才能建立MTU:1440。有没有办法开始连的时候就设置mtu 1440？

### ISSUE THREAD

**Issue by zhiyin-im** [hackgfw/openwrt-gfw#27]
像这样/etc/ppp/ip-up.d/ip-up-wall的开头：
PPP_IFACE="$1";
PPP_TTY="$2";
PPP_SPEED="$3";
PPP_LOCAL="$4";
PPP_REMOTE="$5";
PPP_IPPARAM="$6";
ifconfig $PPP_IFACE mtu 1440
每次都要连N次VPN，先建立MTU:1500，断N次后才能建立MTU:1440。有没有办法开始连的时候就设置mtu 1440？比如在/etc/ppp/options或者/etc/ppp/options.pptp。

**Comment by zhiyin-im** [comment]
在你那不能复现吗？每次要协商N次才能建立mtu 1440。如果设"option mtu 1444"则ifconfig -a pptp-wall的结果就是mtu 1444。如果vpn一直连着都不是问题，但线路不稳定“真正的互联网”断线间隔就难以忍受了。

**Comment by hackgfw** [comment]
我这里目前还没有遇到vpn连接建立不了的情况，从你之前的反馈看，你的vpn连接丢包很高，有试过其他类型的vpn吗？

**Comment by zhiyin-im** [comment]
小区宽带就这样了。现在想解决每次重新连接，mtu 1440要半天才能协商好的问题。每次断5秒10秒没啥感觉，断一分钟两分钟就难以忍受了。

**Comment by zhiyin-im** [comment]
仔细看了日志，就是得协商半天才能mtu 1440。有时一次连接协商不好，还得连好几次。自己搭建的VPN应该没问题，以后换了宽带再看看。

**Comment by zhiyin-im** [comment]
已经很不错了，实在连接不上就重启路由器，应该是小区宽带的问题。
