### ISSUE TITLE
国内域名没有污染问题，但有部分劫持问题，https还没普及呢

### ISSUE THREAD

**Issue by zhiyin-im** [hackgfw/openwrt-gfw#31]
比如插一个广告窗口。虽然目前还不严重，但很无耻很令人愤慨！

**Comment by hackgfw** [comment]
isp的劫持包还是有指纹的，可以识别指纹将isp注入的内容丢掉，但是isp同时还可能向服务器发送rst，导致扔掉了isp的注入内容之后，网页打不开，需要重新刷新才行。
至于指纹如何识别，不同的isp可能方法会有差别，不过一般可以通过ttl,ip id,tcp windows size,tcp flag等来判别
