### ISSUE TITLE
/etc/config/gfw-vpn是怎么调用的？如果用老的方法配置了PPTPVPN，怎么配置通过vpn来dns？

### ISSUE THREAD

**Issue by zhiyin-im** [hackgfw/openwrt-gfw#32]
编译、安装ipk在我的mw4530r上vpn不拨号也没任何日志。。。只能用老办法逐步安装配置。

**Comment by hackgfw** [comment]
你如果压根不安装gfw-vpn，能正常拨号和显示日志吗？按道理gfw-vpn应该不会影响拨号。

**Comment by hackgfw** [comment]
另外关于使用老方法让dns走vpn可以参考 https://github.com/hackgfw/openwrt-gfw/issues/8#issuecomment-26991068

**Comment by zhiyin-im** [comment]
没有gfw-vpn、只修改了内核编译的rom，无法连vpn而且没有任何出错信息；
必须再加上gfw-vpn编译，用factory.bin覆盖；再去掉gfw-vpn编译，用sysupgrade -c sysupgrade.bin升级并保留配置文件；然后逐步安装配置，再修改mtu才可以连上vpn并正常访问google。。。

似乎修改内核之后的rom依赖gfw-vpn的配置文件，比如/etc/config/gfw-vpn？因为刷rom之后opkg包应该都没了，但配置文件还保留着。

**Comment by zhiyin-im** [comment]
我的意思就是新的AntiDNSPoisoning还依赖新的/etc/config/gfw-vpn，虽不影响拨号，但是不起作用的话，启动了新的AntiDNSPoisoning就会导致不能上网，因为dns依赖vpn。

**Comment by hackgfw** [comment]
"必须再加上gfw-vpn编译，用factory.bin覆盖；再去掉gfw-vpn编译，用sysupgrade -c sysupgrade.bin升级并保留配置文件；然后逐步安装配置，再修改mtu才可以连上vpn并正常访问google"
这个过程好复杂啊，如果你看了gfw-vpn的Makefile的话，其实就是帮你拷贝了几个文件而已，不至于先是factory.bin再是sysupgrade才能用，感觉你的固件在某些地方是不是有什么问题？  

另外修改了内核编译的rom也没有什么特殊的地方，和官方固件唯一区别也就是pptp.ko、l2tp.ko、pppox.ko等几个内核模块代码有些差异，实际上我现在一直使用官方固件+自己编译的*.ko，因为我懒得刷固件，里面的配置太多了，不想再重配一遍。  

"似乎修改内核之后的rom依赖gfw-vpn的配置文件"
修改内核应该不依赖任何东西，至于你看到的配置文件还保留着，是因为你用的sysupgrade会保留配置，这也是我从来不用sysupgrade的原因，难保新旧两版的配置不兼容就会导致莫名其妙的错误.

"新的AntiDNSPoisoning还依赖新的/etc/config/gfw-vpn，虽不影响拨号，但是不起作用的话，启动了新的AntiDNSPoisoning就会导致不能上网"
新的AntiDNSPoisoning确实依赖gfw-vpn才能保证不被dns污染，但是就算你没有装gfw-vpn，AntiDNSPoisoning也应该能提供域名解析，只是部分域名会被GFW污染，如果你发现“启动了新的AntiDNSPoisoning就会导致不能上网”，那么一定是某些地方出了意想不到的问题

**Comment by zhiyin-im** [comment]
我在逐步安装配置的PPTPVPN上(可以连VPN/GOOGLE)，按照最新的AntiDNSPoisoning逐步安装设置不能上网，FIREFOX显示一直在解析域名。然后把VPN注释掉，还是不能上网。新的AntiDNSPoisoning还依赖老的AntiDNSPoisoning吗？按说VPN注释掉就该走本地的DNS了。

**Comment by zhiyin-im** [comment]
莫非延迟太高？不是每次都要通过VPN解析DNS吧？应该路由器缓存了一部分DNS，没缓存才查询VPN。

**Comment by hackgfw** [comment]
"FIREFOX显示一直在解析域名"
给我的感觉是你的bind没有启动起来，查看system log下有什么错误信息吗？执行 netstat -an | grep 53 的结果是什么？
新的AntiDNSPoisoning思路是禁用掉dnsmasq的域名解析功能，使用bind做域名解析，如果bind启动不起来，那么路由器及接在路由器下的电脑（除非在电脑上手动配置DNS服务器）就上不了网。
