### ISSUE TITLE
新的AntiDNSPoisoning依赖新PPTPVPN的配置/etc/config/gfw-vpn中的DNS部分

### ISSUE THREAD

**Issue by zhiyin-im** [hackgfw/openwrt-gfw#33]
如果用老的PPTPVPN就没法启动/etc/config/gfw-vpn中的DNS配置，然后DNS不通没法上网。。。即便在/etc/ppp/ip-up.d/ip-up-wall添加了iptables -t mangle -A PREROUTING -p udp --dport 53 -m set ! --match-set whiteip src -m set ! --match-set whiteip dst -m set ! --match-set china dst -j MARK --set-mark 0xffff也不行，只能注掉所有新的AntiDNSPoisoning配置才能上网。

BTW：之前老的AntiDNSPoisoning没法让google以外的网站不被污染，一直凑合着用，实在太需要google之外的国际网站就注掉路由器VPN重启网路再用PC连VPN。

**Comment by hackgfw** [comment]
以前那套配置现在已经没有维护了，没有那么多精力。
如果你一定要用旧版的配置，那么添加路由把8.8.8.8指向从VPN走，然后把所有电脑的DNS改成8.8.8.8吧，这样至少不会被DNS污染，只是少了本地CDN。
