### ISSUE TITLE
OptimizePPTPVPN超赞！路由器vpn连接比ubuntu还稳定！

### ISSUE THREAD

**Issue by zhiyin-im** [hackgfw/openwrt-gfw#34]
如果开p2p下载占用带宽太多(p2p在其它专用NAS，和拨号PC不是相同主机)，VPN几分钟就断，然后ubuntu还没自动重拨功能。。。唯一令人痛恨的就是DNS污染在mw4530r始终无法保证google以外的网站的可访问性，经常不得以掉路由器VPN重启网路再用PC连VPN。。。

**Comment by hackgfw** [comment]
首先你可以将p2p下载的流量通过gfw-vpn分流到本地线路上，其次现在DNS防污染是依赖VPN的，如果你VPN连不上，自然没有办法防污染。

**Comment by hackgfw** [comment]
另外就是用了 OptimizePPTPVPN 之后可以查看 /proc/pptp/* 里的统计信息，具体解释在 OptimizePPTPVPN 里有提到，一般来讲如果丢包过多的话，VPN是不会稳定的

**Comment by elleys** [comment]
@zhiyin-im OptimizePPTPVPN编译之后，是一个什么文件啊？不同设备是不是可以用同一个包，还是要分开编译呢？
我查看了一些资料，单并没有看懂，麻烦您指点一下
http://beamnote.com/2013/general-methods-of-compile-openwrt.html
http://wiki.openwrt.org/doc/howto/build

**Comment by zhiyin-im** [comment]
编译完就是ROM文件，比如
bin/ar71xx/openwrt-ar71xx-generic-mw4530r-v1-squashfs-factory.bin
bin/ar71xx/openwrt-ar71xx-generic-mw4530r-v1-squashfs-sysupgrade.bin
不同设备的ROM大小不同当然不能共用，编译完所有openwrt支持的包都有
