### ISSUE TITLE
如果你看到的是 list network 'wan' 的话，则再加一行 list network 'wall' 即可

### ISSUE THREAD

**Issue by zhiyin-im** [hackgfw/openwrt-gfw#35]
是否可以理解为情况1(黑体为改动的部分)：
config zone
        option name             wan
        **option network          'wan wall'**
        option input            REJECT
        option output           ACCEPT
        option forward          REJECT
        option masq             1
        option mtu_fix          1
情况2(这是**我的配置文件，多一个wan6**)：
config zone
        option name             wan
        **list   network             'wan'
        list   network             'wall'**
        list   network             'wan6'
        option input               REJECT
        option output             ACCEPT
        option forward           REJECT
        option masq              1
        option mtu_fix           1

**Comment by zhiyin-im** [comment]
gfw-vpn编译版，mtd -r write /tmp/openwrt-ar71xx-generic-mw4530r-v1-squashfs-sysupgrade.bin firmware覆盖，VPN没运行迹象，也没日志输出。

配置文件应该没错，和老的逐步配置版PPTPVPN一样。如果pptp组件编译出错，至少应该有出错信息。

**Comment by hackgfw** [comment]
是的，你的理解是正确的。
至于提到的VPN没运行迹象，也没日志输出，我建议你还是用排除法：
1 从 downloads.openwrt.org 下载 factory 官方固件刷机，是否能建立vpn连接？
2 在官方固件的基础上安装gfw-vpn是否还能建立vpn连接？
3 下载官方源代码，但是不使用任何补丁，编译完成后使用factory 固件刷机，是否能建立vpn连接？
4 在上一步自编译固件的基础上安装gfw-vpn是否还能建立vpn连接？
5 下载官方源代码，打上OptimizePPTPVPN补丁，编译完成后使用factory 固件刷机，是否能建立vpn连接？
6 在上一步固件的基础上安装gfw-vpn是否还能建立vpn连接？
