### ISSUE TITLE
怎么调试新版AntiDNSPoisoning？

### ISSUE THREAD

**Issue by zhiyin-im** [hackgfw/openwrt-gfw#37]
搜了下递归DNS，还是没明白原理。老版逐步安装配置PPTPVPN+新版AntiDNSPoisoning，会不停重连VPN。而老版逐步安装配置PPTPVPN本身可以单独正常运行。已经在/etc/ppp/ip-up.d/ip-up-wall添加了iptables -t mangle -A PREROUTING -p udp --dport 53 -m set ! --match-set whiteip src -m set ! --match-set whiteip dst -m set ! --match-set china dst -j MARK --set-mark 0xffff

**Comment by zhiyin-im** [comment]
MTU:1500会不停重连(昨天午睡重连70多次)，无法稳定到MTU:1440。而单独运行PPTPVPN重连最多三次就行。

**Comment by hackgfw** [comment]
用作域名解析的bind有成功启动吗？nslookup www.google.com 有结果吗？
另外网络问题最好能抓包分析，比如具体是什么原因导致断线的，丢包？连接被重置？

**Comment by zhiyin-im** [comment]
好，已经有了稳定(相对)的VPN连接，就差这一点了。推倒狗共的GFW！

**Comment by zhiyin-im** [comment]
新的AntiDNSPoisoning配置步骤最后少了一句：/etc/init.d/named start或者reboot(路由器)
其实这个我懂，只是没多想。。。

bind现在启动了，但跟以前一样只能找到google：
root@OpenWrt:~# nslookup www.google.com
Server:    127.0.0.1
Address 1: 127.0.0.1 localhost

Name:      www.google.com
Address 1: 2404:6800:4005:803::1012
Address 2: 173.194.127.242 hkg03s16-in-f18.1e100.net
Address 3: 173.194.127.244 hkg03s16-in-f20.1e100.net
Address 4: 173.194.127.241 hkg03s16-in-f17.1e100.net
Address 5: 173.194.127.243 hkg03s16-in-f19.1e100.net
Address 6: 173.194.127.240 hkg03s16-in-f16.1e100.net

国内如jd.com正常，但国外github.com还是不正常：
root@OpenWrt:~# nslookup assets-cdn.github.com
Server:    127.0.0.1
Address 1: 127.0.0.1 localhost

nslookup: can't resolve 'assets-cdn.github.com': Name or service not known
root@OpenWrt:~# nslookup github.com
Server:    127.0.0.1
Address 1: 127.0.0.1 localhost

nslookup: can't resolve 'github.com': Name or service not known

**Comment by zhiyin-im** [comment]
nslookup www.google.com返回的还是香港的IP，DNS没走通VPN？已经在/etc/ppp/ip-up.d/ip-up-wall添加了
iptables -t mangle -A PREROUTING -p udp --dport 53 -m set ! --match-set whiteip src -m set ! --match-set whiteip dst -m set ! --match-set china dst -j MARK --set-mark 0xffff
没写对？

/etc/ppp/ip-up.d/ip-up-wall
PPP_IFACE="$1";
PPP_TTY="$2";
PPP_SPEED="$3";
PPP_LOCAL="$4";
PPP_REMOTE="$5";
PPP_IPPARAM="$6";

ip_up_wall() {
        ip route del default via $PPP_REMOTE

        CHKIPSET=$(ipset -L china | wc -l)
        if [ "$CHKIPSET" == "0" ]; then
                ipset -N china nethash --hashsize 32768

                # for IP in $(wget -O - http://www.ipdeny.com/ipblocks/data/countries/cn.zone)
                for IP in $(cat /etc/config/cn.zone)
                do
                        ipset -A china $IP
                done

                ipset -A china 10.0.0.0/8
                ipset -A china 172.16.0.0/12
                ipset -A china 192.168.0.0/16
        fi

        CHKIPSET=$(ipset -L whiteip | wc -l)
        if [ "$CHKIPSET" == "0" ]; then
                ipset -N whiteip iphash --hashsize 128
                for IP in $(cat /etc/config/ip.whitelist)
                do
                        ipset -A whiteip $IP
                done
        fi

        iptables -t mangle -A PREROUTING -p tcp -m set ! --match-set whiteip src -m set ! --match-set whiteip dst -m set ! --match-set china dst -m multiport --dports 80,443,1935 -j MARK --set-mark 0xffff
        iptables -t mangle -A OUTPUT -p tcp -m set ! --match-set whiteip src -m set ! --match-set whiteip dst -m set ! --match-set china dst -m multiport --dports 80,443,1935 -j MARK --set-mark 0xffff
        iptables -t mangle -A FORWARD -p tcp -m set ! --match-set whiteip src -m set ! --match-set whiteip dst -m set ! --match-set china dst -m multiport --dports 80,443,1935 -j MARK --set-mark 0xffff
	iptables -t mangle -A PREROUTING -p udp --dport 53 -m set ! --match-set whiteip src -m set ! --match-set whiteip dst -m set ! --match-set china dst -j MARK --set-mark 0xffff

        CHKIPROUTE=$(grep wall /etc/iproute2/rt_tables)
        if [ -z "$CHKIPROUTE" ]; then
                echo "11 wall" >> /etc/iproute2/rt_tables
        fi

        ip route add table wall default via $PPP_LOCAL
        ip rule add fwmark 0xffff table wall priority 1
}

if [ "$PPP_IFACE" == "pptp-wall" ]; then
        ip_up_wall
fi

**Comment by zhiyin-im** [comment]
root@OpenWrt:~# netstat -an | grep 53
tcp        0      0 192.168.1.110:53        0.0.0.0:*               LISTEN      
tcp        0      0 10.0.0.239:53           0.0.0.0:*               LISTEN      
tcp        0      0 127.0.0.1:53            0.0.0.0:*               LISTEN      
udp        0      0 192.168.1.110:53        0.0.0.0:*                           
udp        0      0 10.0.0.239:53           0.0.0.0:*                           
udp        0      0 127.0.0.1:53            0.0.0.0:*                           

192.168.1.110是拨号的路由器分给openwrt的ip，10.0.0.239是openwrt自己子网的ip

**Comment by hackgfw** [comment]
已经在/etc/ppp/ip-up.d/ip-up-wall添加了
“iptables -t mangle -A PREROUTING -p udp --dport 53 -m set ! --match-set whiteip src -m set ! --match-set whiteip dst -m set ! --match-set china dst -j MARK --set-mark 0xffff”
这是不够的，从路由器自己发出的dns请求是不经过 PREROUTING  的，你还需要按之前的 PREROUTING 、OUTPUT、FORWARD都加上才行

**Comment by zhiyin-im** [comment]
是这样写吗(tcp->udp，80,443,1935>53)？不清楚原理，再确认一下：
iptables -t mangle -A PREROUTING -p udp --dport 53 -m set ! --match-set whiteip src -m set ! --match-set whiteip dst -m set ! --match-set china dst -j MARK --set-mark 0xffff
iptables -t mangle -A OUTPUT -p udp -m set ! --match-set whiteip src -m set ! --match-set whiteip dst -m set ! --match-set china dst -m multiport --dports 53 -j MARK --set-mark 0xffff
iptables -t mangle -A FORWARD -p udp -m set ! --match-set whiteip src -m set ! --match-set whiteip dst -m set ! --match-set china dst -m multiport --dports 53 -j MARK --set-mark 0xffff

**Comment by zhiyin-im** [comment]
ip-down-wall(也仿照上面加了三条)：

PPP_IFACE="$1";
PPP_TTY="$2";
PPP_SPEED="$3";
PPP_LOCAL="$4";
PPP_REMOTE="$5";
PPP_IPPARAM="$6";

ip_down_wall() {
        iptables -t mangle -D PREROUTING -p tcp -m set ! --match-set whiteip src -m set ! --match-set whiteip dst -m set ! --match-set china dst -m multiport --dports 80,443,1935 -j MARK --set-mark 0xffff
        iptables -t mangle -D OUTPUT -p tcp -m set ! --match-set whiteip src -m set ! --match-set whiteip dst -m set ! --match-set china dst -m multiport --dports 80,443,1935 -j MARK --set-mark 0xffff
        iptables -t mangle -D FORWARD -p tcp -m set ! --match-set whiteip src -m set ! --match-set whiteip dst -m set ! --match-set china dst -m multiport --dports 80,443,1935 -j MARK --set-mark 0xffff

        iptables -t mangle -D PREROUTING -p udp -m set ! --match-set whiteip src -m set ! --match-set whiteip dst -m set ! --match-set china dst -m multiport --dports 53 -j MARK --set-mark 0xffff
        iptables -t mangle -D OUTPUT -p udp -m set ! --match-set whiteip src -m set ! --match-set whiteip dst -m set ! --match-set china dst -m multiport --dports 53 -j MARK --set-mark 0xffff
        iptables -t mangle -D FORWARD -p udp -m set ! --match-set whiteip src -m set ! --match-set whiteip dst -m set ! --match-set china dst -m multiport --dports 53 -j MARK --set-mark 0xffff

        ip route del table wall default
        ip rule del priority 1
}

if [ "$PPP_IFACE" == "pptp-wall" ]; then
        ip_down_wall
fi

**Comment by zhiyin-im** [comment]
结果会不停的重启PPTP，莫非GFW检测到VPN DNS特征？PC连VPN都一切正常。

**Comment by zhiyin-im** [comment]
发现重启了network之后重启一下bind就好了！！！
/etc/init.d/network restart
/etc/init.d/named restart
