### ISSUE TITLE
通过mwan3双拨的情况下，请问如何修改mark才能兼容？

### ISSUE THREAD

**Issue by tank8888jx** [hackgfw/openwrt-gfw#38]
通过mwan3双拨的情况下，请问如何修改mark才能兼容？
可否使用load banlance中rule实现https走vpn？

**Comment by hackgfw** [comment]
抱歉，我已经有很多年没用multiwan了，具体现在是怎么实现的不太清楚。如果还是用mark来实现的话要保证multiwan不会将翻墙流量打上mark。

**Comment by tank8888jx** [comment]
我使用了mwan3双拨后 vpn连接成功后好像ip up wall脚本没有执行 是不是脚本获取连接状态的命令需要修改 双拨是通过macvlan虚拟wan口实现的

**Comment by hackgfw** [comment]
是不是接口名字有区别？如果你的vpn连接后名字叫 pptp-vpn ,那么试着把 /etc/config/gfw-vpn 中接口名字也改成 ‘pptp-vpn’ 看看呢？
