### ISSUE TITLE
openwrt的设置复杂了

### ISSUE THREAD

**Issue by zeroly** [hackgfw/openwrt-gfw#58]
我在 /etc/config/dhcp加入
list dhcp_option '6,0.0.0.0'
内网主机的/etc/resolv.conf总是被替换成路由器的IPV6地址导致无法解析。
其实可以使用更简单的方法：
    修改fastdns的默认端口（eg.5353）
    在路由器的/etc/dnsmasq.conf末尾添加
        no-resolv
        server=127.0.0.1#5353

**Comment by hackgfw** [comment]
你遇到的问题其实是 https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=740998
1 你路由器上的 odhcpd 发送 Router Advertisement 声明路由器的ipv6地址上有运行dns服务器
2 内网主机的 rdnssd 会根据收到的 Router Advertisement 数据包覆盖 /etc/resolv.conf 使得结果只有ipv6 dns服务器
3 实际上路由器上运行的 fastdns 并不支持ipv6, 导致内网主机无法进行域名解析

关于1:
如果你启用了 odhcpd 但是没有在 /etc/config/dhcp 中指明ipv6的dns服务器的话, odhcpd会使用路由器的ipv6地址, 配置方法详见 https://wiki.openwrt.org/doc/uci/dhcp#enabling_dhcp_without_enabling_dns 的第二段配置
关于2:
这个问题在 https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=740998 中已经讲得很清楚了, 只要安装 resolvconf 就可以解决
关于3:
目前fastdns不支持tcp, 导致部分只接受tcp的域名解析失败, 准备有空的时候把ipv6和tcp功能加上

PS:
之所以使用dnsmasq正常是因为dnsmasq支持ipv6, 即使内网主机的 /etc/resolv.conf 里只有路由器的ipv6地址, 依然能通过dnsmasq解析域名

**Comment by zeroly** [comment]
明白了

**Comment by praiseslow** [comment]
我是来灌水，看我发帖的头像是什么。
